# PostgreSQL. Versions 8.2 and up are supported.
#
#
development:
  adapter: postgresql
  encoding: unicode
  database: friends_development
  pool: 5
  # username: 
  # password: 
  # template: template0

# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  encoding: unicode
  database: friends_test
  pool: 5
  # username: 
  # password: 
  # template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: friends_production
  pool: 5
  # username: friends
  # password:
  # template: template0
